-- MySQL Script generated by MySQL Workbench
-- Thu Apr  6 16:26:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `sid` INT NOT NULL,
  `sname` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `gpa` VARCHAR(45) NULL,
  PRIMARY KEY (`sid`),
  UNIQUE INDEX `sid_UNIQUE` (`sid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dept` (
  `dname` VARCHAR(45) NOT NULL,
  `numphds` INT NULL,
  PRIMARY KEY (`dname`),
  UNIQUE INDEX `dname_UNIQUE` (`dname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prof` (
  `pname` VARCHAR(45) NOT NULL,
  `dname` VARCHAR(45) NULL,
  PRIMARY KEY (`pname`),
  UNIQUE INDEX `pname_UNIQUE` (`pname` ASC),
  INDEX `dname_idx` (`dname` ASC),
  CONSTRAINT `dname`
    FOREIGN KEY (`dname`)
    REFERENCES `mydb`.`dept` (`dname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `cno` INT NOT NULL,
  `cname` VARCHAR(45) NULL,
  `dname` VARCHAR(45) NULL,
  PRIMARY KEY (`cno`),
  UNIQUE INDEX `cno_UNIQUE` (`cno` ASC),
  INDEX `dname_idx` (`dname` ASC),
  CONSTRAINT `dname`
    FOREIGN KEY (`dname`)
    REFERENCES `mydb`.`dept` (`dname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`major` (
  `dname` VARCHAR(45) NOT NULL,
  `sid` INT NOT NULL,
  PRIMARY KEY (`dname`, `sid`),
  INDEX `sid_idx` (`sid` ASC),
  CONSTRAINT `dname`
    FOREIGN KEY (`dname`)
    REFERENCES `mydb`.`dept` (`dname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `mydb`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`section` (
  `dname` INT NOT NULL,
  `cno` INT NOT NULL,
  `sectno` INT NOT NULL,
  `pname` VARCHAR(45) NULL,
  PRIMARY KEY (`dname`, `cno`, `sectno`),
  INDEX `cno_idx` (`cno` ASC),
  INDEX `pname_idx` (`pname` ASC),
  CONSTRAINT `dname`
    FOREIGN KEY ()
    REFERENCES `mydb`.`dept` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cno`
    FOREIGN KEY (`cno`)
    REFERENCES `mydb`.`course` (`cname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pname`
    FOREIGN KEY (`pname`)
    REFERENCES `mydb`.`prof` (`pname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enroll` (
  `sid` INT NOT NULL,
  `grade` INT NULL,
  `dname` VARCHAR(45) NOT NULL,
  `cno` INT NOT NULL,
  `sectno` INT NOT NULL,
  PRIMARY KEY (`sid`, `dname`, `cno`, `sectno`),
  INDEX `dname_idx` (`dname` ASC),
  INDEX `cno_idx` (`cno` ASC),
  INDEX `sectno_idx` (`sectno` ASC),
  CONSTRAINT `sid`
    FOREIGN KEY (`sid`)
    REFERENCES `mydb`.`student` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dname`
    FOREIGN KEY (`dname`)
    REFERENCES `mydb`.`dept` (`dname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cno`
    FOREIGN KEY (`cno`)
    REFERENCES `mydb`.`course` (`cno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sectno`
    FOREIGN KEY (`sectno`)
    REFERENCES `mydb`.`section` (`dname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
